import type { ArtifactRecord, RunInfo } from "./utils.js";

const ARTIFACT_ORDER: Record<string, number> = {
  RAW_REQUIREMENT: 1,
  CLARIFIED_REQUIREMENT: 2,
  BUSINESS_RULES: 3,
  ACCEPTANCE_CRITERIA: 4,
  OPEN_QUESTIONS: 5,
  ASSUMPTIONS: 6,
  SCOPE_DEFINITION: 7,
  TECHNICAL_DESIGN: 8,
  API_DESIGN: 9,
  DB_DESIGN: 10,
  TASK_BREAKDOWN: 11,
  JIRA_READY_TASKS: 12,
  CODING_PLAN: 13,
  TEST_MATRIX: 14,
  TEST_RESULT: 15,
  FAILED_TESTS: 16,
  IMPLEMENTATION_PROMPT: 17,
  AGENT_LOG: 18,
  DIFF_PATCH: 19,
  CHANGED_FILES: 20,
  FINAL_REPORT: 21,
};

function artifactTypeLabel(type: string): string {
  return type
    .replace(/_/g, " ")
    .toLowerCase()
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

function buildCoverPage(runInfo: RunInfo, title: string): string {
  const lines: string[] = [];
  lines.push(`# ${title}`);
  lines.push("");
  lines.push(`> **Generated by CodeClaw** — ${new Date().toISOString().slice(0, 10)}`);
  lines.push("");
  lines.push("## Run Information");
  lines.push("");
  lines.push(`| Field | Value |`);
  lines.push("|---|---|");
  lines.push(`| Run ID | \`${runInfo.id}\` |`);
  lines.push(`| Mode | ${runInfo.mode} |`);
  lines.push(`| Status | ${runInfo.status} |`);
  lines.push(`| Output Language | ${runInfo.outputLanguage} |`);
  lines.push(`| Created | ${runInfo.createdAt} |`);
  lines.push(`| Exported | ${new Date().toISOString()} |`);
  lines.push("");
  lines.push("---");
  lines.push("");
  return lines.join("\n");
}

function buildTableOfContents(artifacts: ArtifactRecord[]): string {
  const lines: string[] = [];
  lines.push("## Table of Contents");
  lines.push("");

  const sorted = [...artifacts]
    .filter((a) => a.content)
    .sort((a, b) => {
      const orderA = ARTIFACT_ORDER[a.type] ?? 99;
      const orderB = ARTIFACT_ORDER[b.type] ?? 99;
      return orderA - orderB;
    });

  for (const artifact of sorted) {
    const name = artifact.name.replace(/\.(md|json)$/, "").replace(/-/g, " ");
    const label = name.charAt(0).toUpperCase() + name.slice(1);
    const anchor = artifact.type.toLowerCase().replace(/_/g, "-");
    lines.push(`- [${label}](#${anchor})`);
  }

  lines.push("");
  lines.push("---");
  lines.push("");
  return lines.join("\n");
}

interface CombinedMdOptions {
  title: string;
}

export function buildDeliveryPackageMarkdown(
  runInfo: RunInfo,
  artifacts: ArtifactRecord[],
  options: CombinedMdOptions,
): string {
  const sections: string[] = [];

  sections.push("---");
  sections.push(`title: "${options.title}"`);
  sections.push(`run_id: ${runInfo.id}`);
  sections.push(`mode: ${runInfo.mode}`);
  sections.push(`status: ${runInfo.status}`);
  sections.push(`generated_at: ${new Date().toISOString()}`);
  sections.push("---");
  sections.push("");

  sections.push(buildCoverPage(runInfo, options.title));
  sections.push(buildTableOfContents(artifacts));

  const sorted = [...artifacts]
    .filter((a) => a.content)
    .sort((a, b) => {
      const orderA = ARTIFACT_ORDER[a.type] ?? 99;
      const orderB = ARTIFACT_ORDER[b.type] ?? 99;
      return orderA - orderB;
    });

  for (const artifact of sorted) {
    const label = artifactTypeLabel(artifact.type);

    sections.push(`## ${label}`);
    sections.push("");
    sections.push(`> **File:** \`${artifact.name}\``);
    sections.push("");
    sections.push(artifact.content ?? "");
    sections.push("");
    sections.push("---");
    sections.push("");
  }

  return sections.join("\n");
}
