import { describe, it, expect } from "vitest";
import { convertMdToHtml } from "./mdToHtml.js";
import { buildCombinedMarkdown, tocFromMarkdown } from "./utils.js";

describe("mdToHtml", () => {
  const sampleMd = `# Test Document

## Section 1

This is a paragraph with **bold** text.

### Subsection

- Item 1
- Item 2

## Section 2

| Col 1 | Col 2 |
|-------|-------|
| A     | B     |
`;

  it("converts markdown to HTML", async () => {
    const html = await convertMdToHtml(sampleMd, {
      title: "Test Document",
      cssTheme: "simple",
      includeTableOfContents: false,
      includeHeader: false,
      includeFooter: false,
    });
    expect(html).toContain("<h1>Test Document</h1>");
    expect(html).toContain("Section 1");
    expect(html).toContain("<strong>bold</strong>");
    expect(html).toContain("<table");
    expect(html).toContain("</html>");
  });

  it("includes table of contents when enabled", async () => {
    const html = await convertMdToHtml(sampleMd, {
      title: "Test",
      cssTheme: "simple",
      includeTableOfContents: true,
      includeHeader: false,
      includeFooter: false,
    });
    expect(html).toContain("Table of Contents");
  });

  it("includes header and footer when enabled", async () => {
    const html = await convertMdToHtml(sampleMd, {
      title: "Test",
      cssTheme: "simple",
      includeTableOfContents: false,
      includeHeader: true,
      includeFooter: true,
    });
    expect(html).toContain('class="header"');
    expect(html).toContain('class="footer"');
    expect(html).toContain("Generated by CodeClaw");
  });

  it("loads different CSS themes", async () => {
    const professional = await convertMdToHtml("# Test", {
      title: "Test",
      cssTheme: "professional",
      includeTableOfContents: false,
      includeHeader: false,
      includeFooter: false,
    });
    const modern = await convertMdToHtml("# Test", {
      title: "Test",
      cssTheme: "modern",
      includeTableOfContents: false,
      includeHeader: false,
      includeFooter: false,
    });
    expect(professional).toContain("Georgia");
    expect(modern).toContain("Inter");
  });

  it("handles empty markdown", async () => {
    const html = await convertMdToHtml("", {
      title: "Empty",
      includeTableOfContents: false,
      includeHeader: false,
      includeFooter: false,
    });
    expect(html).toContain("<body>");
    expect(html).toContain("</body>");
  });
});

describe("buildCombinedMarkdown", () => {
  it("combines artifacts into single document", () => {
    const artifacts = [
      {
        id: "1",
        runId: "test",
        type: "requirement",
        name: "clarified-requirement.md",
        path: "/test/clarified-requirement.md",
        format: "markdown",
        content: "# Requirement\n\nThis is the requirement.",
      },
      {
        id: "2",
        runId: "test",
        type: "design",
        name: "technical-design.md",
        path: "/test/technical-design.md",
        format: "markdown",
        content: "# Design\n\nThis is the design.",
      },
    ];

    const result = buildCombinedMarkdown(artifacts, "Test Run");
    expect(result).toContain("# Test Run");
    expect(result).toContain("## Clarified requirement");
    expect(result).toContain("This is the requirement.");
    expect(result).toContain("## Technical design");
    expect(result).toContain("This is the design.");
  });

  it("handles empty artifacts", () => {
    const result = buildCombinedMarkdown([], "Empty");
    expect(result).toContain("# Empty");
  });
});

describe("tocFromMarkdown", () => {
  it("generates TOC from headings", () => {
    const md = `# Title\n\n## Section 1\n\n### Sub 1\n\n## Section 2\n`;
    const toc = tocFromMarkdown(md);
    expect(toc).toContain("Title");
    expect(toc).toContain("Section 1");
    expect(toc).toContain("Sub 1");
    expect(toc).toContain("Section 2");
  });
});
