import type * as PlaywrightTypes from "playwright";

export interface PdfOptions {
  title: string;
  pageSize?: "A4" | "Letter";
  margin?: { top: number; right: number; bottom: number; left: number };
}

export async function convertHtmlToPdf(htmlContent: string, options: PdfOptions): Promise<Buffer> {
  let playwrightModule: typeof PlaywrightTypes;

  try {
    playwrightModule = await import("playwright");
  } catch {
    throw new Error(
      "PDF export requires Playwright and Chromium.\n" +
        "Install: npx playwright install chromium\n" +
        "Or try: codeclaw export --format docx\n" +
        "Or try: codeclaw export --format html",
    );
  }

  const pageSize = options.pageSize ?? "A4";
  const margin = options.margin ?? { top: 20, right: 20, bottom: 20, left: 20 };

  let browser;
  try {
    browser = await playwrightModule.chromium.launch({ headless: true });
    const page = await browser.newPage();
    await page.setContent(htmlContent, { waitUntil: "networkidle" });
    const pdfBuffer = await page.pdf({
      format: pageSize,
      margin: {
        top: String(margin.top) + "mm",
        right: String(margin.right) + "mm",
        bottom: String(margin.bottom) + "mm",
        left: String(margin.left) + "mm",
      },
      printBackground: true,
      displayHeaderFooter: true,
      headerTemplate: "<div></div>",
      footerTemplate: `<div style="font-size:9px;text-align:center;width:100%;color:#999;">Generated by CodeClaw &mdash; Page <span class="pageNumber"></span> of <span class="totalPages"></span></div>`,
    });
    return Buffer.from(pdfBuffer);
  } catch (error) {
    throw new Error(
      `PDF conversion failed: ${error instanceof Error ? error.message : String(error)}\n` +
        "Ensure Chromium is installed: npx playwright install chromium",
    );
  } finally {
    if (browser) {
      await browser.close();
    }
  }
}
