import { marked } from "marked";
import { readFile } from "node:fs/promises";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { tocFromMarkdown } from "./utils.js";

export interface HtmlDocumentOptions {
  title: string;
  cssTheme?: "professional" | "simple" | "modern";
  includeTableOfContents?: boolean;
  includeHeader?: boolean;
  includeFooter?: boolean;
}

const THEMES: Record<string, string> = {
  professional: "professional.css",
  simple: "simple.css",
  modern: "modern.css",
};

const CURRENT_DIR: string = dirname(fileURLToPath(import.meta.url));

async function loadTheme(name: string): Promise<string> {
  const themeFile = THEMES[name] ?? "professional.css";
  try {
    return await readFile(join(CURRENT_DIR, "themes", themeFile), "utf-8");
  } catch {
    return "";
  }
}

export async function convertMdToHtml(
  markdownContent: string,
  options: HtmlDocumentOptions,
): Promise<string> {
  const theme = options.cssTheme ?? "professional";
  const css = await loadTheme(theme);

  const htmlBody = await marked.parse(markdownContent);

  const toc = options.includeTableOfContents !== false ? tocFromMarkdown(markdownContent) : "";

  const title = options.title || "Untitled Document";
  const date = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const headerHtml =
    options.includeHeader !== false
      ? `<div class="header"><h1>${title}</h1><div class="meta">${date}</div></div>`
      : "";

  const footerHtml =
    options.includeFooter !== false
      ? `<div class="footer">Generated by CodeClaw &mdash; Page 1</div>`
      : "";

  const tocHtml =
    options.includeTableOfContents !== false && toc
      ? `<div class="toc"><h2>Table of Contents</h2><ul>${toc
          .split("\n")
          .map(
            (line) =>
              `<li>${line.replace(/^\s*-\s+/, "").replace(/\[([^\]]+)\]\([^)]+\)/, "$1")}</li>`,
          )
          .join("")}</ul></div>`
      : "";

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title}</title>
  <style>${css}</style>
</head>
<body>
  ${headerHtml}
  ${tocHtml}
  ${htmlBody}
  ${footerHtml}
</body>
</html>`;
}
