import { readFile, readdir } from "node:fs/promises";
import { join, relative } from "node:path";

export interface ArtifactRecord {
  id: string;
  runId: string;
  type: string;
  name: string;
  path: string;
  format: string;
  content?: string;
}

export interface RunInfo {
  id: string;
  title: string;
  rawRequirement: string;
  mode: string;
  outputLanguage: string;
  status: string;
  createdAt: string;
}

export async function collectArtifactContents(
  artifacts: ArtifactRecord[],
): Promise<ArtifactRecord[]> {
  return Promise.all(
    artifacts.map(async (a) => {
      if (a.content) return a;
      try {
        const content = await readFile(a.path, "utf-8");
        return { ...a, content };
      } catch {
        return a;
      }
    }),
  );
}

export async function collectFilesFromRun(
  runDir: string,
): Promise<{ name: string; path: string }[]> {
  const files: { name: string; path: string }[] = [];

  async function walk(dir: string) {
    const entries = await readdir(dir, { withFileTypes: true });
    for (const entry of entries) {
      const fullPath = join(dir, entry.name);
      if (entry.isDirectory()) {
        await walk(fullPath);
      } else {
        const rel = relative(runDir, fullPath);
        files.push({ name: rel, path: fullPath });
      }
    }
  }

  await walk(runDir);
  return files;
}

export function buildCombinedMarkdown(artifacts: ArtifactRecord[], title: string): string {
  const lines: string[] = [];

  lines.push(`# ${title}`);
  lines.push("");
  lines.push(`> Generated by AITeam on ${new Date().toISOString().slice(0, 10)}`);
  lines.push("");

  for (const artifact of artifacts) {
    if (!artifact.content) continue;
    const sectionName = artifact.name.replace(/\.(md|json)$/, "").replace(/-/g, " ");
    const sectionTitle = sectionName.charAt(0).toUpperCase() + sectionName.slice(1);

    lines.push("");
    lines.push(`## ${sectionTitle}`);
    lines.push("");
    lines.push(artifact.content);
    lines.push("");
    lines.push("---");
    lines.push("");
  }

  return lines.join("\n");
}

export function tocFromMarkdown(markdown: string): string {
  const lines: string[] = [];
  const headingRegex = /^(#{1,6})\s+(.+)$/gm;
  let match: RegExpExecArray | null;

  while ((match = headingRegex.exec(markdown)) !== null) {
    const headingText = match[1] ?? "";
    const level = headingText.length;
    const text = match[2] ?? "";
    const indent = "  ".repeat(level - 1);
    const anchor = text
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/(^-|-$)/g, "");
    lines.push(`${indent}- [${text}](#${anchor})`);
  }

  return lines.join("\n");
}
