import type { WorkflowTemplate } from "@codeclaw/shared";

export const DEFAULT_WORKFLOW_TEMPLATES: Omit<
  WorkflowTemplate,
  "workflowTemplateId" | "createdAt" | "updatedAt" | "projectId"
>[] = [
  {
    name: "Docs Only",
    description: "Generate documentation artifacts without code execution",
    isDefault: true,
    steps: [
      {
        id: "ba",
        name: "BA Analysis",
        agentName: "BA",
        enabled: true,
        producesArtifacts: true,
        order: 0,
        kind: "requirements",
      },
      {
        id: "ux-research",
        name: "UX Research",
        agentName: "UX Researcher",
        enabled: true,
        producesArtifacts: true,
        order: 1,
        kind: "ui_ux",
      },
      {
        id: "ui-design",
        name: "UI Design",
        agentName: "UI Designer",
        enabled: true,
        producesArtifacts: true,
        order: 2,
        kind: "ui_ux",
      },
      {
        id: "ux-writing",
        name: "UX Writing",
        agentName: "UX Writer",
        enabled: true,
        producesArtifacts: true,
        order: 3,
        kind: "ui_ux",
      },
      {
        id: "architect",
        name: "Architecture Design",
        agentName: "Architect",
        enabled: true,
        producesArtifacts: true,
        order: 4,
        kind: "architecture",
      },
      {
        id: "frontend",
        name: "Frontend Planning",
        agentName: "Frontend Planner",
        enabled: true,
        producesArtifacts: true,
        order: 5,
        kind: "frontend_plan",
      },
      {
        id: "backend",
        name: "Backend Planning",
        agentName: "Backend Planner",
        enabled: true,
        producesArtifacts: true,
        order: 6,
        kind: "backend_plan",
      },
      {
        id: "pm",
        name: "Task Breakdown",
        agentName: "PM",
        enabled: true,
        producesArtifacts: true,
        order: 7,
        kind: "tasks",
      },
      {
        id: "qa",
        name: "Test Planning",
        agentName: "QA",
        enabled: true,
        producesArtifacts: true,
        order: 8,
        kind: "testing",
      },
      {
        id: "traceability",
        name: "Traceability",
        agentName: "Traceability Agent",
        enabled: true,
        producesArtifacts: true,
        order: 9,
        kind: "documentation",
      },
      {
        id: "reporter",
        name: "Final Report",
        agentName: "Reporter",
        enabled: true,
        producesArtifacts: true,
        order: 10,
        kind: "final_report",
      },
    ],
  },
  {
    name: "Assisted (with Code)",
    description: "Full assisted workflow with code generation and review",
    isDefault: false,
    steps: [
      {
        id: "ba",
        name: "BA Analysis",
        agentName: "BA",
        enabled: true,
        producesArtifacts: true,
        order: 0,
        kind: "requirements",
      },
      {
        id: "architect",
        name: "Architecture Design",
        agentName: "Architect",
        enabled: true,
        producesArtifacts: true,
        order: 1,
        kind: "architecture",
      },
      {
        id: "pm",
        name: "Task Breakdown",
        agentName: "PM",
        enabled: true,
        producesArtifacts: true,
        order: 2,
        kind: "tasks",
      },
      {
        id: "qa",
        name: "Test Planning",
        agentName: "QA",
        enabled: true,
        producesArtifacts: true,
        order: 3,
        kind: "testing",
      },
      {
        id: "developer",
        name: "Code Generation",
        agentName: "Developer",
        enabled: true,
        requiresApproval: true,
        producesArtifacts: true,
        order: 4,
        kind: "coding_execution",
      },
      {
        id: "reviewer",
        name: "Code Review",
        agentName: "Reviewer",
        enabled: true,
        producesArtifacts: true,
        order: 5,
        kind: "review",
      },
      {
        id: "reporter",
        name: "Final Report",
        agentName: "Reporter",
        enabled: true,
        producesArtifacts: true,
        order: 6,
        kind: "final_report",
      },
    ],
  },
  {
    name: "Semi-Auto (Full Workflow)",
    description: "Complete workflow including research, design, code, test, and review",
    isDefault: false,
    steps: [
      {
        id: "ba",
        name: "BA Analysis",
        agentName: "BA",
        enabled: true,
        producesArtifacts: true,
        order: 0,
        kind: "requirements",
      },
      {
        id: "ux-research",
        name: "UX Research",
        agentName: "UX Researcher",
        enabled: true,
        producesArtifacts: true,
        order: 1,
        kind: "ui_ux",
      },
      {
        id: "ui-design",
        name: "UI Design",
        agentName: "UI Designer",
        enabled: true,
        producesArtifacts: true,
        order: 2,
        kind: "ui_ux",
      },
      {
        id: "architect",
        name: "Architecture Design",
        agentName: "Architect",
        enabled: true,
        producesArtifacts: true,
        order: 3,
        kind: "architecture",
      },
      {
        id: "frontend",
        name: "Frontend Planning",
        agentName: "Frontend Planner",
        enabled: true,
        producesArtifacts: true,
        order: 4,
        kind: "frontend_plan",
      },
      {
        id: "backend",
        name: "Backend Planning",
        agentName: "Backend Planner",
        enabled: true,
        producesArtifacts: true,
        order: 5,
        kind: "backend_plan",
      },
      {
        id: "pm",
        name: "Task Breakdown",
        agentName: "PM",
        enabled: true,
        producesArtifacts: true,
        order: 6,
        kind: "tasks",
      },
      {
        id: "qa",
        name: "Test Planning",
        agentName: "QA",
        enabled: true,
        producesArtifacts: true,
        order: 7,
        kind: "testing",
      },
      {
        id: "developer",
        name: "Code Generation",
        agentName: "Developer",
        enabled: true,
        requiresApproval: true,
        producesArtifacts: true,
        order: 8,
        kind: "coding_execution",
      },
      {
        id: "reviewer",
        name: "Code Review",
        agentName: "Reviewer",
        enabled: true,
        producesArtifacts: true,
        order: 9,
        kind: "review",
      },
      {
        id: "reporter",
        name: "Final Report",
        agentName: "Reporter",
        enabled: true,
        producesArtifacts: true,
        order: 10,
        kind: "final_report",
      },
    ],
  },
];

export interface WorkflowTemplateSeedState {
  projectId: string | undefined;
  seededAt: string;
  templateIds: string[];
}

const SEED_NAME = "default-workflow-templates-v1";

export function getSeedName(): string {
  return SEED_NAME;
}
