import { readFile } from "node:fs/promises";
import { join } from "node:path";
import type { ArtifactPaths } from "../artifacts/artifactWriter.js";

interface RunRecord {
  id: string;
  title: string;
  requirement: string;
  mode: string;
  status: string;
}

export interface PRSummary {
  title: string;
  body: string;
}

async function readFileSafe(filePath: string): Promise<string | null> {
  try {
    return await readFile(filePath, "utf-8");
  } catch {
    return null;
  }
}

export async function generatePRSummary(
  runId: string,
  paths: ArtifactPaths,
  run: RunRecord,
): Promise<PRSummary> {
  const title = `[AITeam] ${run.title}`;

  const bodyParts: string[] = [];

  bodyParts.push(`## Summary`);
  bodyParts.push(``);
  bodyParts.push(`**Run ID:** ${runId}`);
  bodyParts.push(`**Mode:** ${run.mode}`);
  bodyParts.push(`**Status:** ${run.status}`);
  bodyParts.push(`**Title:** ${run.title}`);
  bodyParts.push(``);

  const requirementContent = await readFileSafe(
    join(paths.requirementDir, "clarified-requirement.md"),
  );
  if (requirementContent) {
    bodyParts.push(`## Requirement`);
    bodyParts.push(``);
    const summaryLine = extractSummaryLine(requirementContent);
    bodyParts.push(summaryLine ?? requirementContent.slice(0, 500));
    bodyParts.push(``);
  }

  const changedFilesContent = await readFileSafe(paths.changedFilesPath);
  if (changedFilesContent) {
    bodyParts.push(`## Changes`);
    bodyParts.push(``);
    try {
      const parsed: { files: string[] } = JSON.parse(changedFilesContent) as {
        files: string[];
      };
      for (const file of parsed.files) {
        bodyParts.push(`- \`${file}\``);
      }
    } catch {
      const files = changedFilesContent.split("\n").filter(Boolean);
      for (const file of files) {
        bodyParts.push(`- \`${file}\``);
      }
    }
    bodyParts.push(``);
  }

  const testResultContent = await readFileSafe(join(paths.testsDir, "test-result.md"));
  if (testResultContent) {
    bodyParts.push(`## Test Results`);
    bodyParts.push(``);
    bodyParts.push(testResultContent.slice(0, 1000));
    bodyParts.push(``);
  }

  const reviewContent = await readFileSafe(join(paths.reportDir, "review-report.md"));
  if (reviewContent) {
    bodyParts.push(`## Review Status`);
    bodyParts.push(``);
    const summaryLine = extractSummaryLine(reviewContent);
    bodyParts.push(summaryLine ?? reviewContent.slice(0, 500));
    bodyParts.push(``);
  }

  const traceabilityContent = await readFileSafe(paths.traceabilityMd);
  if (traceabilityContent) {
    bodyParts.push(`## Traceability`);
    bodyParts.push(``);
    bodyParts.push(traceabilityContent.slice(0, 1000));
    bodyParts.push(``);
  }

  bodyParts.push(`---`);
  bodyParts.push(``);
  bodyParts.push(`## Generated by AITeam`);
  bodyParts.push(``);
  bodyParts.push(`- Run ID: \`${runId}\``);
  bodyParts.push(``);

  return {
    title,
    body: bodyParts.join("\n"),
  };
}

function extractSummaryLine(content: string): string | null {
  const lines = content.split("\n");
  for (const line of lines) {
    const trimmed = line.trim();
    if (
      trimmed.startsWith("**Summary:**") ||
      trimmed.startsWith("**Status:**") ||
      trimmed.startsWith("## Summary")
    ) {
      return trimmed;
    }
    if (trimmed.length > 0 && !trimmed.startsWith("#")) {
      return trimmed.slice(0, 200);
    }
  }
  return null;
}
