import { describe, it, expect, vi, beforeEach } from "vitest";

vi.mock("node:fs/promises", () => ({
  readFile: vi.fn(),
}));

import { readFile } from "node:fs/promises";
import { generatePRSummary } from "./prSummaryGenerator.js";

const mockReadFile = readFile as unknown as ReturnType<typeof vi.fn>;

const mockPaths = {
  runDir: "/test/.ai-team/runs/run_123",
  inputFile: "/test/.ai-team/runs/run_123/input.md",
  requirementDir: "/test/.ai-team/runs/run_123/requirement",
  scopeDir: "/test/.ai-team/runs/run_123/scope",
  scopeDefinitionPath: "/test/.ai-team/runs/run_123/scope/product-goal.md",
  outOfScopePath: "/test/.ai-team/runs/run_123/scope/out-of-scope.md",
  successCriteriaPath: "/test/.ai-team/runs/run_123/scope/success-criteria.md",
  designDir: "/test/.ai-team/runs/run_123/design",
  tasksDir: "/test/.ai-team/runs/run_123/tasks",
  testsDir: "/test/.ai-team/runs/run_123/tests",
  implementationDir: "/test/.ai-team/runs/run_123/implementation",
  implementationPromptPath: "/test/.ai-team/runs/run_123/implementation/implementation-prompt.md",
  agentLogPath: "/test/.ai-team/runs/run_123/implementation/agent-output.log",
  diffPatchPath: "/test/.ai-team/runs/run_123/implementation/diff.patch",
  changedFilesPath: "/test/.ai-team/runs/run_123/implementation/changed-files.json",
  reportDir: "/test/.ai-team/runs/run_123/report",
  logsDir: "/test/.ai-team/runs/run_123/logs",
  traceabilityMd: "/test/.ai-team/runs/run_123/report/traceability.md",
  traceabilityJson: "/test/.ai-team/runs/run_123/report/traceability.json",
  snapshotDir: "/test/.ai-team/runs/run_123/snapshots",
  testResultPath: "/test/.ai-team/runs/run_123/tests/test-result.md",
  failedTestsPath: "/test/.ai-team/runs/run_123/tests/failed-tests.json",
  reviewDir: "/test/.ai-team/runs/run_123/review",
  reviewReportPath: "/test/.ai-team/runs/run_123/review/review-report.md",
  securityReviewPath: "/test/.ai-team/runs/run_123/review/security-review.md",
  requirementCoveragePath: "/test/.ai-team/runs/run_123/review/requirement-coverage.md",
  fixLoopDir: "/test/.ai-team/runs/run_123/implementation/fix-loop",
  uxDir: "/test/.ai-team/runs/run_123/ux",
  userJourneyPath: "/test/.ai-team/runs/run_123/ux/user-journey.md",
  uxDesignPath: "/test/.ai-team/runs/run_123/ux/ux-design.md",
  uxCopyPath: "/test/.ai-team/runs/run_123/ux/ux-copy.md",
  componentBreakdownPath: "/test/.ai-team/runs/run_123/ux/component-breakdown.md",
  frontendDesignPath: "/test/.ai-team/runs/run_123/design/frontend-design.md",
  backendDesignPath: "/test/.ai-team/runs/run_123/design/backend-design.md",
};

const mockRun = {
  id: "run_123",
  title: "Add login page",
  requirement: "Add user login page",
  mode: "docs-only",
  status: "REPORT_GENERATED",
};

beforeEach(() => {
  vi.clearAllMocks();
});

describe("prSummaryGenerator", () => {
  it("generates PR summary without artifacts", async () => {
    mockReadFile.mockRejectedValue(new Error("not found"));

    const summary = await generatePRSummary("run_123", mockPaths, mockRun);
    expect(summary.title).toBe("[AITeam] Add login page");
    expect(summary.body).toContain("run_123");
    expect(summary.body).toContain("Generated by AITeam");
  });

  it("includes requirement section when available", async () => {
    mockReadFile
      .mockResolvedValueOnce("# Clarified Requirement\nUser can login")
      .mockRejectedValueOnce(new Error("not found"))
      .mockRejectedValueOnce(new Error("not found"))
      .mockRejectedValueOnce(new Error("not found"))
      .mockRejectedValueOnce(new Error("not found"));

    const summary = await generatePRSummary("run_123", mockPaths, mockRun);
    expect(summary.title).toBe("[AITeam] Add login page");
    expect(summary.body).toContain("Requirement");
    expect(summary.body).toContain("User can login");
  });

  it("includes changed files section", async () => {
    mockReadFile
      .mockRejectedValueOnce(new Error("not found"))
      .mockResolvedValueOnce(JSON.stringify({ files: ["src/login.tsx", "src/auth.ts"] }))
      .mockRejectedValueOnce(new Error("not found"))
      .mockRejectedValueOnce(new Error("not found"))
      .mockRejectedValueOnce(new Error("not found"));

    const summary = await generatePRSummary("run_123", mockPaths, mockRun);
    expect(summary.body).toContain("login.tsx");
    expect(summary.body).toContain("auth.ts");
  });

  it("includes traceability section", async () => {
    mockReadFile
      .mockRejectedValueOnce(new Error("not found"))
      .mockRejectedValueOnce(new Error("not found"))
      .mockRejectedValueOnce(new Error("not found"))
      .mockRejectedValueOnce(new Error("not found"))
      .mockResolvedValueOnce("## Traceability\n| REQ-001 | Covered |");

    const summary = await generatePRSummary("run_123", mockPaths, mockRun);
    expect(summary.body).toContain("Traceability");
  });
});
