import { redactSecrets } from "@codeclaw/shared";

export interface ExecutionReportInput {
  adapterName: string;
  command: string;
  workingDirectory: string;
  dryRun: boolean;
  startTime: string;
  endTime: string;
  durationMs: number;
  exitCode: number | null;
  stdoutSummary: string;
  stderrSummary: string;
  changedFiles: string[];
  success: boolean;
  gitDiffSummary: string | undefined;
  nextSteps: string[] | undefined;
}

export function generateOpenCodeExecutionReport(input: ExecutionReportInput): string {
  const lines: string[] = [];

  lines.push("# OpenCode Execution Report\n");

  lines.push("## Summary\n");
  lines.push(`- **Adapter:** ${input.adapterName}`);
  lines.push(`- **Dry Run:** ${input.dryRun ? "Yes" : "No"}`);
  lines.push(`- **Status:** ${input.success ? "✅ Success" : "❌ Failed"}`);
  lines.push(`- **Working Directory:** \`${input.workingDirectory}\``);
  lines.push("");

  lines.push("## Timing\n");
  lines.push(`- **Started:** ${input.startTime}`);
  lines.push(`- **Ended:** ${input.endTime}`);
  lines.push(`- **Duration:** ${formatDuration(input.durationMs)}`);
  lines.push("");

  lines.push("## Exit Information\n");
  lines.push(`- **Exit Code:** ${input.exitCode !== null ? String(input.exitCode) : "N/A"}`);
  lines.push(`- **Command:** \`${redactSecrets(input.command)}\``);
  lines.push("");

  if (input.stdoutSummary) {
    const redactedStdout = redactSecrets(input.stdoutSummary);
    lines.push("## Standard Output\n");
    lines.push("```");
    lines.push(truncateOutput(redactedStdout, 2000));
    lines.push("```\n");
  }

  if (input.stderrSummary) {
    const redactedStderr = redactSecrets(input.stderrSummary);
    lines.push("## Standard Error\n");
    lines.push("```");
    lines.push(truncateOutput(redactedStderr, 1000));
    lines.push("```\n");
  }

  if (input.changedFiles.length > 0) {
    lines.push("## Changed Files\n");
    for (const file of input.changedFiles) {
      lines.push(`- \`${file}\``);
    }
    lines.push("");
  } else if (!input.dryRun) {
    lines.push("## Changed Files\n");
    lines.push("No files were changed.\n");
  }

  if (input.gitDiffSummary && input.changedFiles.length > 0) {
    lines.push("## Git Diff Summary\n");
    lines.push("```diff");
    lines.push(truncateOutput(input.gitDiffSummary, 3000));
    lines.push("```\n");
    lines.push("> **Note:** A full diff patch file is available in the run artifacts directory.\n");
  } else if (input.changedFiles.length > 0) {
    lines.push("> **TODO:** Add Git Diff Review step to capture detailed diff analysis.\n");
  }

  if (input.nextSteps && input.nextSteps.length > 0) {
    lines.push("## Next Steps\n");
    for (const step of input.nextSteps) {
      lines.push(`- ${step}`);
    }
    lines.push("");
  }

  if (input.success) {
    lines.push("## Verification\n");
    lines.push("Run the following commands to verify the changes:\n");
    lines.push("```bash");
    lines.push("# Build the project");
    lines.push("pnpm build");
    lines.push("");
    lines.push("# Run tests");
    lines.push("pnpm test");
    lines.push("");
    lines.push("# Lint check");
    lines.push("pnpm lint");
    lines.push("");
    lines.push("# Type check");
    lines.push("pnpm typecheck");
    lines.push("```\n");
  }

  if (!input.success) {
    lines.push("## Troubleshooting\n");
    lines.push("The execution did not complete successfully. Possible causes:\n");
    lines.push("- OpenCode CLI may have encountered an error during execution");
    lines.push("- The implementation prompt may be too large or malformed");
    lines.push("- Network or permission issues may have occurred");
    lines.push("- The timeout may have been exceeded");
    lines.push("\nReview the standard error output above for details.\n");
  }

  lines.push("---\n");
  lines.push(
    "_Report generated by CodeClaw OpenCode adapter at " + new Date().toISOString() + "_\n",
  );

  return lines.join("\n");
}

function formatDuration(ms: number): string {
  const seconds = Math.floor(ms / 1000);
  const minutes = Math.floor(seconds / 60);
  const remainingSeconds = seconds % 60;
  if (minutes > 0) {
    return `${String(minutes)}m ${String(remainingSeconds)}s`;
  }
  return `${String(remainingSeconds)}s`;
}

function truncateOutput(text: string, maxLength: number): string {
  if (text.length <= maxLength) {
    return text;
  }
  return text.slice(0, maxLength) + `\n... [output truncated at ${String(maxLength)} characters]`;
}
