import {
  isGhCliAvailable,
  isGhAuthenticated,
  getCurrentRepo,
  createGhPR,
  getGhPRStatus,
  getGhPRView,
  getCIRuns,
  getGhCliVersion,
} from "./gitHubCliService.js";

export interface GitHubConfig {
  enabled: boolean;
  mode?: string;
  owner?: string;
  repo?: string;
}

export interface PRSummaryInput {
  runId: string;
  title: string;
  body: string;
  baseBranch?: string;
}

export interface PRSummaryResult {
  success: boolean;
  prUrl?: string;
  error?: string;
}

export interface GitHubStatus {
  available: boolean;
  authenticated: boolean;
  version: string | null;
  currentRepo: { owner: string; repo: string } | null;
  configured: boolean;
  configOwner?: string;
  configRepo?: string;
}

export interface CheckStatusResult {
  ghCliAvailable: boolean;
  ghAuthenticated: boolean;
  ghVersion: string | null;
  currentRepo: { owner: string; repo: string } | null;
  configValid: boolean;
  overall: "ok" | "not_available" | "not_authenticated" | "no_repo";
}

export interface TestConnectionResult {
  success: boolean;
  message: string;
  details?: {
    ghCliAvailable: boolean;
    ghAuthenticated: boolean;
    currentRepo: { owner: string; repo: string } | null;
  };
}

export interface CIRunInfo {
  workflow: string;
  status: string;
  conclusion: string;
}

export interface PRInfo {
  state: string;
  title: string;
  url: string;
  number: number;
}

export async function checkStatus(config: GitHubConfig): Promise<CheckStatusResult> {
  if (!config.enabled) {
    return {
      ghCliAvailable: false,
      ghAuthenticated: false,
      ghVersion: null,
      currentRepo: null,
      configValid: false,
      overall: "not_available",
    };
  }

  const ghCliAvailable = await isGhCliAvailable();
  const ghAuthenticated = ghCliAvailable ? await isGhAuthenticated() : false;
  const ghVersion = ghCliAvailable ? await getGhCliVersion() : null;
  const currentRepo = ghAuthenticated ? await getCurrentRepo() : null;

  let overall: CheckStatusResult["overall"] = "ok";
  if (!ghCliAvailable) {
    overall = "not_available";
  } else if (!ghAuthenticated) {
    overall = "not_authenticated";
  } else if (!currentRepo) {
    overall = "no_repo";
  }

  return {
    ghCliAvailable,
    ghAuthenticated,
    ghVersion,
    currentRepo,
    configValid: ghCliAvailable && ghAuthenticated,
    overall,
  };
}

export async function testConnection(config: GitHubConfig): Promise<TestConnectionResult> {
  if (!config.enabled) {
    return {
      success: false,
      message:
        "GitHub integration is not enabled. Enable it in config or run 'codeclaw config set integrations.github.enabled true'.",
    };
  }

  const ghCliAvailable = await isGhCliAvailable();
  if (!ghCliAvailable) {
    return {
      success: false,
      message: "GitHub CLI (gh) is not installed. Install it from https://cli.github.com/",
    };
  }

  const ghAuthenticated = await isGhAuthenticated();
  if (!ghAuthenticated) {
    return {
      success: false,
      message: "Not authenticated with GitHub CLI. Run: gh auth login",
    };
  }

  const currentRepo = await getCurrentRepo();

  return {
    success: true,
    message: currentRepo
      ? `Connected to ${currentRepo.owner}/${currentRepo.repo}`
      : "Authenticated but no GitHub repo detected in current directory",
    details: {
      ghCliAvailable,
      ghAuthenticated,
      currentRepo,
    },
  };
}

export function generatePRSummary(
  runId: string,
  _artifacts: Record<string, string>,
): PRSummaryInput {
  return {
    runId,
    title: `[CodeClaw] Run ${runId}`,
    body: generatePRBody(runId, _artifacts),
  };
}

function generatePRBody(runId: string, artifacts: Record<string, string>): string {
  const lines: string[] = [];
  lines.push(`## Summary`);
  lines.push(``);
  lines.push(`Run ID: ${runId}`);
  lines.push(``);

  if (artifacts.requirement) {
    lines.push(`## Requirement`);
    lines.push(``);
    lines.push(artifacts.requirement);
    lines.push(``);
  }

  if (artifacts.changedFiles) {
    lines.push(`## Changes`);
    lines.push(``);
    const files = artifacts.changedFiles.split("\n").filter(Boolean);
    for (const file of files) {
      lines.push(`- ${file}`);
    }
    lines.push(``);
  }

  if (artifacts.testResults) {
    lines.push(`## Test Results`);
    lines.push(``);
    lines.push(artifacts.testResults);
    lines.push(``);
  }

  if (artifacts.reviewSummary) {
    lines.push(`## Review Status`);
    lines.push(``);
    lines.push(artifacts.reviewSummary);
    lines.push(``);
  }

  if (artifacts.traceability) {
    lines.push(`## Traceability`);
    lines.push(``);
    lines.push(artifacts.traceability);
    lines.push(``);
  }

  lines.push(`---`);
  lines.push(``);
  lines.push(`Generated by CodeClaw`);
  lines.push(`- Run ID: ${runId}`);
  lines.push(``);

  return lines.join("\n");
}

export async function createPR(summary: PRSummaryInput): Promise<PRSummaryResult> {
  try {
    const options: { base?: string; draft?: boolean } = {};
    if (summary.baseBranch !== undefined && summary.baseBranch !== "") {
      options.base = summary.baseBranch;
    }
    const result = await createGhPR(summary.title, summary.body, options);
    return {
      success: true,
      prUrl: result.url,
    };
  } catch (e) {
    return {
      success: false,
      error: e instanceof Error ? e.message : String(e),
    };
  }
}

export async function readCIRun(): Promise<CIRunInfo[]> {
  return getCIRuns();
}

export async function readPRStatus(): Promise<PRInfo[]> {
  const prs = await getGhPRStatus();
  return prs.map((p) => ({
    state: p.state,
    title: p.title,
    url: p.url,
    number: p.number,
  }));
}

export async function readPRDetail(
  prNumber: number,
): Promise<{ state: string; title: string; body: string; url: string } | null> {
  return getGhPRView(prNumber);
}
